spring:
  datasource:
    username: root
    url: jdbc:postgresql://localhost:5432/queue
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

public:
  key: classpath:public-key